name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet restore ./YourSolution.sln

      - name: Build
        run: dotnet build ./YourSolution.sln -c Release --no-restore /warnaserror

      - name: Test
        run: dotnet test ./YourSolution.sln -c Release --no-build --verbosity minimal
